### ISSUE TITLE
No longer works after update

### ISSUE THREAD

**Issue by noahrepublic** [axdaxis/robloxaudiodownloaderissues#1]
sadly, i am here for the same reason you are about to be, finding a new way to do it since my bot broke lmk if you find anything

**Comment by axdaxis** [comment]
Did you try reinstalling the extension? also do you have any other Roblox extensions installed? and what audio is it?

**Comment by noahrepublic** [comment]
Tried on 2 different audios and reinstalled twice.

**Comment by axdaxis** [comment]
Could you send the audios? Do you have access to them/own them?

**Comment by noahrepublic** [comment]
no i do not own them, but I have the links https://www.roblox.com/library/5830749378/

**Comment by noahrepublic** [comment]
I am trying to find a way to download none owned items as my bot broke

**Comment by axdaxis** [comment]
Sorry, I can't actually help with that. The way I get the audio URLs basically broke on private audio pages, so I can't fix it. If I can find a way, I'll update this thread, but for know, you're outta luck.
also, for this audio, 
> https://www.roblox.com/library/5830749378/

the source is this. [Online Social Hangout - ROBLOX](https://www.youtube.com/watch?v=OBUlpvyInzg)
