### ISSUE TITLE
Certain audio cant be downloaded

### ISSUE THREAD

**Issue by marsbar16** [axdaxis/robloxaudiodownloaderissues#2]
I was downloading Roblox sounds for a mod, however a certain audio **https://create.roblox.com/marketplace/asset/6326880642/AK47-Shoot-CBRO** can't seem to be downloaded. I assume it's due to it having an invalid letter which prevents it from being downloaded, just my guess.

**Comment by axdaxis** [comment]
Yeah, it seems like that's the issue. It should be an easy fix, so I'll reply when the extension is updated.

**Comment by marsbar16** [comment]
Found another one, periods are maybe also affected? https://create.roblox.com/marketplace/asset/4608582637/44Magnum1

**Comment by axdaxis** [comment]
Alright, I've pushed out an update (1.91) to the Chrome Web Store fixing the issues, but it still has to go through review, so I'll close the issue when the update has been approved.

**Comment by marsbar16** [comment]
Awesome.

**Comment by axdaxis** [comment]
1.91 has been pushed, should've fixed the issue. Closing.
https://chrome.google.com/webstore/detail/roblox-audio-downloader/beonfijfkkhcdidijfmiohnajkpinled
