### ISSUE TITLE
Compressed audio download ?

### ISSUE THREAD

**Issue by milanomaster** [axdaxis/robloxaudiodownloaderissues#3]
I downloaded an audio and it felt as if something was missing compared to the upload on Roblox
I know there's something with 128 / 352 kbps and eh... is it ever possible that the downloaded audio gets compressed and loses some of its quality?

Tried to compare a Sound Effect I uploaded myself (and own the file to) to the same SFX when downloaded:

Attempt to display comparison
![image](https://github.com/Dax009YT/robloxaudiodownloaderissues/assets/66282423/dbbac995-376f-43f0-a725-1fc287bd5694)

Not sure **if** that's the case, but it does sound a bit less rich. Is it ever possible that the Extension (very useful by the way, especially since the new roblox update) lowers the quality?

**Comment by axdaxis** [comment]
I think Roblox may just be compressing the audio on upload, but I'll do my own checks to confirm.

**Comment by milanomaster** [comment]
Hm, believe that's correct also. Checked with the file and the roblox upload; the uploaded one seems a tad bit flatter also. 
I'm no expert on code so eh... can you 'choose' which audio quality you extract from the website, where it'd be limited to only the initial upload compression (if that's also the case and I'm not imagining things)?

**Comment by axdaxis** [comment]
Alright, I've done some testing, and it seems like Roblox is compressing the audio on upload. The extension doesn't do any compression or audio modifying when downloading (with the exception of the file name changing from some random characters to the name of the audio), so it seems that it's on Roblox's side, unfortunately.

**Comment by milanomaster** [comment]
Good to know. Thank you! 👍
