### ISSUE TITLE
Support for private audios

### ISSUE THREAD

**Issue by MarioGladiator** [axdaxis/robloxaudiodownloaderissues#4]
I found some apis which might help in getting private audios working: https://economy.roblox.com/v2/assets/{asset_id}/details, https://assetdelivery.roproxy.com/v2/assetId/batch. That is all I just really want support for private audios since there is a certain audio that I need lmk if it works or not

**Comment by axdaxis** [comment]
I'll look into this. Don't know about the private audio thing working, though

**Comment by MarioGladiator** [comment]
> I'll look into this. Don't know about the private audio thing working, though

Alright, good luck :)
